# Generated by Django 4.2.1 on 2023-05-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanastaBasicaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('precio_promedio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CanastaBasicaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('anual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canastasBasicasMensuales', to='canasta.canastabasicaanual')),
            ],
        ),
    ]
