# Generated by Django 4.2.1 on 2023-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canasta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canastabasicaanual',
            name='inflacion',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
