# Generated by Django 4.2.1 on 2023-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canasta", "0002_canastabasicaanual_inflacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canastabasicaanual",
            name="inflacion",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
