# Generated by Django 4.2.1 on 2023-06-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canasta", "0003_alter_canastabasicaanual_inflacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canastabasicaanual",
            name="precio_promedio",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
